### ISSUE TITLE
zeromq22 isn't available

### ISSUE THREAD

**Issue by kevinburke** [gopherds/gophernotes#26]
The README says to install zeromq22. If I run `brew tap homebrew/versions && brew search zeromq` here are the available options:

```
homebrew/versions/zeromq32                                                                homebrew/versions/zeromq405                                                               zeromq ✔
```

I don't know whether zeromq32 works or not, I'm doing the the rest of the install now.

**Comment by kevinburke** [comment]
It looks like it was removed here: https://github.com/Homebrew/homebrew-versions/commit/e102cc897ae1330b021c10f128197546b29ac543

**Comment by dwhitena** [comment]
Hi @kevinburke.  You should be able to install with an updated version of zeroMQ.  You will just need to run `go get` with the right tag.  E.g., 

```
go get -tags zmq_4_x github.com/gophergala2016/gophernotes
```

Could you try that and see how it goes?  If it works, we can hopefully update the OSX instructions accordingly.

**Comment by santagada** [comment]
With this tag and brew install zeromq it works so go ahead and update docs :)

**Comment by dwhitena** [comment]
Done.
