### ISSUE TITLE
jupyter 4.1 stores config in $HOME/.jupyter

### ISSUE THREAD

**Issue by kevinburke** [gopherds/gophernotes#27]
The installation guide recommends installing to ~/.local/share, but the documented configuration directory is `$HOME/.jupyter`. If you run `jupyter --config-dir`, it should confirm this. The documentation also mentions this: http://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html?highlight=JUPYTER_CONFIG_DIR

**Comment by kevinburke** [comment]
further down I think it points to the correct location for Macs being `~/Library/Jupyter`, though you can change this with the JUPYTER_PATH env var

**Comment by dwhitena** [comment]
@kevinburke Yeah, I have had some trouble getting the installation guide correct for OSX.  Could you possibly recommend some changes based on the above (because do not run OSX).  That would be hugely appreciated.

**Comment by kevinburke** [comment]
> Could you possibly recommend some changes based on the above (because do not run OSX).

I guess just mentioning in the update guide that you should set `JUPYTER_PATH` or the Mac install location is `~/Library/Jupyter`

**Comment by dwhitena** [comment]
This seems to be the same issue as here: https://github.com/gopherds/gophernotes/issues/25.  Although, now that I'm readying the above documentation, I think I should update the docs again.  Working on it.

**Comment by dwhitena** [comment]
Ok, I think the README is in order now.  Could you take a look and see if it makes sense to you @kevinburke?

**Comment by dwhitena** [comment]
My understanding is that the README is nor accurate for OSX.  Closing.
