### ISSUE TITLE
Docker run command with docker for mac

### ISSUE THREAD

**Issue by gianluca-sabena** [gopherds/gophernotes#43]
On mac os X with docker for mac the command to run is `docker run  -p 8888:8888 --rm  dwhitena/gophernotes jupyter notebook --no-browser --ip=0.0.0.0`

It may be useful to update readme page

**Comment by tabetomo** [comment]
Thanks. It works for my mac!

Since the port 8888 is used in local jupyer, I used 9000 port as: 
docker run -p 9000:8888 --rm dwhitena/gophernotes jupyter notebook --no-browser --ip=0.0.0.0

**Comment by dwhitena** [comment]
Thanks @gianluca-sabena and @tabetomo!  I updated the README.  Although I used the `-d` flag assuming people will want to run as a daemon.
