### ISSUE TITLE
lots of "error: exit status 2" in the logs

### ISSUE THREAD

**Issue by kevinburke** [gopherds/gophernotes#51]
The logs display a lot of "exit status 2" messages without any further explanation of what went wrong or compiled incorrectly. Examples (I think):

Passing an incorrect type as a function arg
Referencing a variable that does not exist
Calling a function in a package without importing the package

Looks like this in the terminal:

```
[I 10:43:33.504 NotebookApp] Kernel restarted: 750c7c9c-da9a-4a2c-a1c4-64e0dc9d5195
[I 10:43:33.661 NotebookApp] Adapting to protocol v4.0 for kernel 750c7c9c-da9a-4a2c-a1c4-64e0dc9d5195
error: exit status 2
error: exit status 2
[I 10:45:20.245 NotebookApp] Saving file at /base58.ipynb
error: exit status 2
```

On the other hand I did get this error message once:

/var/folders/dx/x6gx95t14n7bb3v878968fkm0000gn/T/952273222/func_proxy.go:4:4: expected declaration, found 'for'

**Comment by dwhitena** [comment]
@kevinburke Thanks.  Yes, we need to address this.  We need to sweep through the `repl` package and address error handling in general.

**Comment by dwhitena** [comment]
@kevinburke I think this is fixed in the latest release (v0.2.0).  It is at least fixed for many of these `exit status 2` things.  Now, when there is actually an error, it will return it to the notebook (I think).  Please try it out and see if it is more useful, and if any other weirdness cropped up.  Thanks again!

**Comment by dwhitena** [comment]
Actually, I think I already see some weirdness.  Now errors are being returned when they shouldn't be (e.g., for thing defined but not used, which is something we want in a notebook).

**Comment by dwhitena** [comment]
Ok, try v0.2.1.  I think most of the weirdness is gone.

**Comment by dwhitena** [comment]
Closing this, as I think the weirdness is gone.

**Comment by kevinburke** [comment]
I think so too!


--
Kevin Burke
925.271.7005 | kev.inburke.com
