### ISSUE TITLE
Install locally on OS X

### ISSUE THREAD

**Issue by connercowling** [gopherds/gophernotes#53]
Getting the following on `go get -tags zmq_4_5 github.com/gopherds/gophernotes` not working :

```
could not determine kind of name for C.ZMQ_HWM
could not determine kind of name for C.ZMQ_MCAST_LOOP
could not determine kind of name for C.ZMQ_RECOVERY_IVL_MSEC
could not determine kind of name for C.ZMQ_SWAP
```

pkg-config: 0.28
zmq 4.1.5

**Comment by dwhitena** [comment]
Hi @connercowling, try literally:

```
go get -tags zmq_4_x github.com/gopherds/gophernotes
```

with the `x` not the `5`.  I think that is the syntax.  Let me know if this does not work.

**Comment by connercowling** [comment]
Doh! I assumed that was a placeholder for the version and never looked back. Thanks.
