### ISSUE TITLE
Missing Windows support

### ISSUE THREAD

**Issue by wdscxsj** [gopherds/gophernotes#56]
First of all, thanks a lot for this amazing project. But Windows support is missing... I can prepare a PR if it helps.

AFAIK, the change is minimal: 

- conditionally disabled 7 lines involving `pkg-config` in `vendor/github.com/alecthomas/gozmq`
- use a .bat file to set `CGO_CFLAGS` and `CGO_LDFLAGS` before invoking `go build`

Including pre-built zmq binaries may be convenient. Or even provide gophernotes.exe for download? :smile:

**Comment by dwhitena** [comment]
@wdscxsj, sorry I was out on vacation last week.  Yes, I haven't considered Windows yet, and if you could PR, that would be amazing and much appreciated!  I don't have a windows machine to test.

**Comment by wdscxsj** [comment]
@dwhitena, PR submitted. This is my first PR on GitHub, so please don't hesitate to point out anything improper.

In particular, prebuilt zmq dependency is included, because not all Windows users like to configure and build C/C++ code.

Quite awkwardly, to link to zmq, MinGW or something else has to be used... Maybe prebuilt gophernotes programs for Windows?

(It's late in my time zone now. I'll pick up your suggestion tomorrow and refine the PR.)

**Comment by wdscxsj** [comment]
Glad the PR helps. Closing this issue now.
